// <auto-generated />
using System;
using MecanicaWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MecanicaWeb.Migrations
{
    [DbContext(typeof(MecanicaWebContext))]
    [Migration("20190503003627_AgendaProfissionalTeste")]
    partial class AgendaProfissionalTeste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MecanicaWeb.Models.Atendimento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Clienteid");

                    b.Property<DateTime>("data");

                    b.Property<string>("descricao");

                    b.Property<DateTime>("hora");

                    b.Property<int>("status");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.ToTable("Atendimento");
                });

            modelBuilder.Entity("MecanicaWeb.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ativo");

                    b.Property<double>("cpf");

                    b.Property<DateTime>("dataDeNascimento");

                    b.Property<string>("email");

                    b.Property<string>("endereco");

                    b.Property<string>("estadoCivil");

                    b.Property<double>("fone");

                    b.Property<string>("nome");

                    b.Property<string>("sexo");

                    b.HasKey("id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("MecanicaWeb.Models.Atendimento", b =>
                {
                    b.HasOne("MecanicaWeb.Models.Cliente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("Clienteid");
                });
#pragma warning restore 612, 618
        }
    }
}
